In [106]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
from numpy.linalg import inv
data=pd.read_excel("Data.xlsx",header=None)
X=data[[0,1]]
y=data[2]
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
n=x_train[0].count()
sum_x1=0
sum_x2=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x2x2=0
sum_x1y1=0
sum_x2y1=0
for i in range(0,n):
    sum_x1=sum_x1+x_train[0][i]
    sum_x2=sum_x2+x_train[1][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train[0][i]*x_train[0][i]
    sum_x1x2=sum_x1x2+x_train[0][i]*x_train[1][i]
    sum_x2x2=sum_x2x2+x_train[1][i]*x_train[1][i]
    sum_x1y1=sum_x1y1+x_train[0][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train[1][i]*y_train[i]
A = np.array([[n, sum_x1, sum_x2], [sum_x1, sum_x1x1, sum_x1x2],[sum_x2,sum_x1x2,sum_x2x2]])
B=np.array([sum_y1, sum_x1y1, sum_x2y1])
Inverse=inv(A)
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]
W=np.array([w0,w1,w2])
print(W)

    

[681.34825732   4.52127649 -12.31770487]


In [107]:
np.around(Inverse @ A).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [109]:
dEbydw0=A[0][0]*w0+A[0][1]*w1+A[0][2]*w2-sum_y1

In [113]:
abs(np.around(dEbydw0))

0.0

In [111]:
dEbydw1=A[1][0]*w0+A[1][1]*w1+A[1][2]*w2-sum_x1y1

In [114]:
abs(np.around(dEbydw1))

0.0

In [115]:
dEbydw2=A[2][0]*w0+A[2][1]*w1+A[2][2]*w2-sum_x2y1

In [116]:
abs(np.around(dEbydw2))

0.0

In [117]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train, y_train)

In [118]:
reg.coef_

array([  4.52127649, -12.31770488])

In [119]:
reg.intercept_

681.3482577091703

In [127]:
y_pred=w0+w1*data[1]+w2*data[2]
MSE=0
m=x_test.count()[0]
for i in range(0,m):
    MSE=MSE+(y_pred-y_test[i])*(y_pred-y_test[i])
print(MSE)

0         6.501763e+10
1         6.374888e+10
2         6.270048e+10
3         6.226479e+10
4         6.194668e+10
5         6.040248e+10
6         5.938875e+10
7         5.932123e+10
8         5.923860e+10
9         5.960563e+10
10        6.017257e+10
11        6.236769e+10
12        6.378058e+10
13        6.368287e+10
14        6.200366e+10
15        6.097351e+10
16        6.233589e+10
17        6.284240e+10
18        6.216988e+10
19        3.557365e+10
20        4.144158e+10
21        4.908732e+10
22        5.486297e+10
23        6.503733e+10
24        6.527221e+10
25        7.169732e+10
26        7.218572e+10
27        5.363014e+10
28        5.755950e+10
29        5.129286e+10
              ...     
434844    4.624183e+10
434845    4.596785e+10
434846    4.543148e+10
434847    4.611583e+10
434848    4.687831e+10
434849    4.693466e+10
434850    3.859756e+10
434851    4.938696e+10
434852    4.976734e+10
434853    4.908588e+10
434854    4.908637e+10
434855    4.874646e+10
434856    4

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)